services:
    nginx:
        image: nginx:latest
        volumes:
            - .:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8080:80"
        environment:
            - NGINX_HOST=localhost
            - NGINX_PORT=80
    php-fpm:
        build:
            context: .
            dockerfile: ./docker/php-fpm/Dockerfile
        volumes:
            - .:/var/www
    php-cli:
        build:
            context: .
            dockerfile: ./docker/php-cli/Dockerfile
        volumes:
            - .:/var/www
        tty: true
    db:
        image: mysql:8.0.30
        ports:
            - "13306:3306"
        env_file:
            - .env
    node:
        image: node:18-alpine
        volumes:
            - .:/var/www
        working_dir: /var/www
        tty: true
